name: GCATs
description: GCATs server resources.

resource_pack:
  pack_format: 63
  name: "{{ project_name }}"
  description: "{{ project_description }}"
  load:
    - resources/VanillaTweaks_MC1.21.x.zip
    - https://cdn.modrinth.com/data/tPtjib62/versions/DovTdPov/visual_armor_trims_3.1_1.21.5%2B.zip
    - https://cdn.modrinth.com/data/6gN7YVi7/versions/fSRRUZQU/Re-covered.zip
    - https://cdn.modrinth.com/data/OhzX8kDf/versions/2ooqPmZH/Theone%27s%20Eating%20Animation%20Pack%20v1.01.zip
    - https://cdn.modrinth.com/data/ivUZsvzp/versions/AQvH8uLq/better_flame_particles-v2.2-mc1.14x-1.21x-resourcepack.zip
    - https://github.com/RedSyven/player-locator/raw/fc904f041444621ae243d09228c88f1ac2b3a7a7/RedSyven's%20Player%20Locator%20Resourcepack%201-21-5+.zip

pipeline:
  - beet.contrib.copy_files

meta:
  copy_files:
    resource_pack:
      pack.png: server-icon.png

output: build/resourcepack
