require:
  - datapack.cascades
  - beet.contrib.unknown_files
  - beet.contrib.auto_yaml
  - beet.contrib.format_json

name: GCATs
description: GCATs server resources.

resource_pack:
  load:
    - resourcepack/VanillaTweaks_MC1.21.x.zip
    - https://cdn.modrinth.com/data/tPtjib62/versions/w7MCM1Bk/visual_armor_trims_4.1.zip
    - https://cdn.modrinth.com/data/6gN7YVi7/versions/4z5iFY64/Re-covered.zip
    - https://cdn.modrinth.com/data/OhzX8kDf/versions/4if0gBBN/Theone%27s%20Eating%20Animation%20Pack%20v1.0.zip
    - https://cdn.modrinth.com/data/ivUZsvzp/versions/5zlKz15s/better_flame_particles-v3.1-mc1.21.9%2B-resourcepack.zip
    - https://cdn.modrinth.com/data/zp6touiL/versions/43cYxPZ8/Just-Atlas_RP_v2-1_1-21-5.zip
    - resourcepack/remove-too-expensive
    - datapack/balanced_beginnings

  zipped: true

  name: "{{ project_name }}-resourcepack"
  description: "{{ project_description }}"
  pack_format: 75

data_pack:
  load:
    - datapack/anti creeper grief v1.1.15 (MC 1.21-1.21.11).zip
    - datapack/double shulker shells v1.3.15 (MC 1.21-1.21.11).zip
    - datapack/more effective tools v1.0.9 (MC 1.21-1.21.11).zip
    - datapack/VanillaTweaks_CraftingTweaks_MC1.21-1.21.11.zip
    - datapack/modally_stranded
    - datapack/clifftree-tweaks
    - datapack/balanced_beginnings

  zipped: true

  name: "{{ project_name }}-datapack"
  description: "{{ project_description }}"
  pack_format: 94

pipeline:
  - beet.contrib.copy_files
  - beet.contrib.auto_yaml
  - beet.contrib.vanilla.load_vanilla
  - beet_plugins.patches.add_entry_replacement_to_loot_tables
  - beet_plugins.patches.json_patch
  - beet.contrib.format_json

meta:
  copy_files:
    resource_pack:
      pack.png: server-icon.png
    data_pack:
      pack.png: server-icon.png
  load_vanilla:
    match:
      loot_table: "*"
      recipe: "*_bed"
  add_entry_replacement_to_loot_tables:
    source: minecraft:rotten_flesh
    target: gcats:cloth
    skip:
      - camel_husk
      - zombie_nautilus
      - zombie_horse
      - zoglin

output: build
