require:
  - beet_plugins.mergeables

name: GCATs
description: GCATs server resources.

resource_pack:
  load:
    - resourcepack/VanillaTweaks_MC1.21.x.zip
    - https://cdn.modrinth.com/data/tPtjib62/versions/G6ZoMPyA/visual_armor_trims_4.0_1.21.5%2B.zip
    # This resource pack attempts to add license information to the pack.mcmeta
    # in a way that is incorrect syntax, at least for mcbeet. I've replaced it
    # with a patched version
    # - https://cdn.modrinth.com/data/6gN7YVi7/versions/q4F6AFtc/Re-covered.zip
    - resourcepack/Re-covered/Re-covered/
    - https://cdn.modrinth.com/data/OhzX8kDf/versions/qw5e9mrm/Theone%27s%20Eating%20Animation%20Pack%20v1.0.zip
    - https://cdn.modrinth.com/data/ivUZsvzp/versions/5zlKz15s/better_flame_particles-v3.1-mc1.21.9%2B-resourcepack.zip
    - https://cdn.modrinth.com/data/zp6touiL/versions/43cYxPZ8/Just-Atlas_RP_v2-1_1-21-5.zip
    - resourcepack/remove-too-expensive

  name: "{{ project_name }}-resourcepack"
  description: "{{ project_description }}"
  pack_format: 69

data_pack:
  load:
    - https://cdn.modrinth.com/data/hl5OLM95/versions/NocMg9CU/Geophilic%20v3.4.4%20f15-88.dp.zip
    - https://cdn.modrinth.com/data/8oi3bsk5/versions/RFNry3l0/Terralith_1.21.5_v2.5.13.zip
    - https://cdn.modrinth.com/data/wXiGiyGX/versions/89fEq6Tf/Amplified_Nether_1.21_v1.2.10.zip
    - https://cdn.modrinth.com/data/lWDHr9jE/versions/8yP0B193/tectonic-datapack-3.0.13.zip
    - https://cdn.modrinth.com/data/bQ5TJA1E/versions/XWHqqNCU/Continents_1.21_v1.1.11.zip
    - https://cdn.modrinth.com/data/iv9jp2k9/versions/TUuYWOJe/lithosphere%201.7%2015.08.2025.zip
    - https://cdn.modrinth.com/data/BuWCQzqf/versions/cn9MTN70/hopobetterunderwaterruins-1-21-10-1-2-5.zip
    - https://cdn.modrinth.com/data/9IxCUYAP/versions/E4SgyyKV/hopobettermineshaft-1-21-10-1-3-4.zip
    - https://cdn.modrinth.com/data/hIpLSyga/versions/DLYnIfCA/hopobetterruinedportals-1-21-10-1-4-8.zip
    - datapack/anti creeper grief v1.1.14 (MC 1.21-1.21.10).zip
    - datapack/double shulker shells v1.3.14 (MC 1.21-1.21.10).zip
    - datapack/more effective tools v1.0.8 (MC 1.21-1.21.10).zip
    - datapack/VanillaTweaks_c214290_MC1.21-1.21.10.zip
    - datapack/modally_stranded

  name: "{{ project_name }}-datapack"
  description: "{{ project_description }}"
  pack_format: 88

pipeline:
  - beet.contrib.copy_files

meta:
  copy_files:
    resource_pack:
      pack.png: server-icon.png
    data_pack:
      pack.png: server-icon.png

output: build
