[[packs]]
url = "https://github.com/RedSyven/player-locator/raw/fc904f041444621ae243d09228c88f1ac2b3a7a7/RedSyven's%20Player%20Locator%20Resourcepack%201-21-5+.zip"

[[packs]]
url = "https://cdn.modrinth.com/data/ivUZsvzp/versions/AQvH8uLq/better_flame_particles-v2.2-mc1.14x-1.21x-resourcepack.zip"

[[packs]]
url = "https://cdn.modrinth.com/data/OhzX8kDf/versions/2ooqPmZH/Theone%27s%20Eating%20Animation%20Pack%20v1.01.zip"

[[packs]]
url = "https://cdn.modrinth.com/data/6gN7YVi7/versions/fSRRUZQU/Re-covered.zip"

[[packs]]
url = "https://cdn.modrinth.com/data/tPtjib62/versions/DovTdPov/visual_armor_trims_3.1_1.21.5%2B.zip"
