require-resource-pack=true
resource-pack-prompt="\\u00a7f\\u00a7o\\u00a7lThis server\\u00a7f makes some texture changes and adds new Vanilla+ content \\u26cf\\n\\u00a7cThis resource pack is \\u00a7brequired, \\u00a7cand without it there will be \\u00a7dmissing textures"
