extends: default
locale: en_US.UTF-8

yaml-files:
- '*.yml'

rules:
  line-length: disable
  indentation: disable
  document-start: disable

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
