name = "GCATs"
version = "v0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "030f0ed55f4ca94e8d7944f27496547b9724646abad4bf9a61b57c18f3277915"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.21.5"
fabric = "0.16.14"
