name: PR Manual Testing Label Checks

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, edited]

jobs:
  require-manual-testing-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required manual testing labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(l => l.name);
            const hasNeedsManualTesting = labels.includes('needs-manual-testing');
            const testableLabels = ['resourcepack', 'datapack'];
            
            let errors = [];
            if (hasNeedsManualTesting) {
              for (const label of testableLabels) {
                if (labels.includes(label)) {
                  const testedLabel = `tested:${label}`;
                  if (!labels.includes(testedLabel)) {
                    errors.push(`PR has labels "${label}" and "needs-manual-testing" but is missing "${testedLabel}" label.`);
                  }
                }
              }
            }
            if (errors.length > 0) {
              core.setFailed(errors.join('\n'));
            } else {
              core.info('Manual testing label requirements satisfied.');
            }
